# Generated by Django 5.0.6 on 2024-06-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='taskTile',
            new_name='taskTitle',
        ),
    ]
