# Generated by Django 5.0.6 on 2024-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_tasktile_tasks_tasktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
